# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f57f6bf31ca47b6bf8ada372beb58391"
name = "upsell Cart Products"
handle = "upsell-cart-products"
application_url = "https://believe-debian-co-sailing.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "wisdom-app-setup.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_checkouts,write_checkouts,write_discounts,write_products"

[auth]
redirect_urls = [
  "https://believe-debian-co-sailing.trycloudflare.com/auth/callback",
  "https://believe-debian-co-sailing.trycloudflare.com/auth/shopify/callback",
  "https://believe-debian-co-sailing.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
